name = "Hugo Flex"
license = "Apache-2.0"
licenselink = "https://github.com/ldeso/hugo-flex/blob/master/LICENSE"
description = "A lightweight Hugo theme leveraging CSS Flexbox."
homepage = "https://github.com/ldeso/hugo-flex/"
demosite = "https://ldeso.github.io/hugo-flex-demo/"
tags = ["blog", "dark mode", "flexbox", "minimal", "multilingual", "no-javascript", "responsive"]
features = ["blog", "contact form", "dark mode", "multilingual", "posts"]
min_version = "0.100"

[author]
  name = "LÃ©o de Souza"
  homepage = "https://github.com/ldeso/"
