name = "Hugo Flex"
license = "Apache-2.0"
licenselink = "https://github.com/de-souza/hugo-flex/blob/master/LICENSE"
description = "A lightweight Hugo theme leveraging CSS Flexbox"
homepage = "https://github.com/de-souza/hugo-flex/"
tags = ["responsive", "minimal", "flexbox", "no-javascript"]
features = ["posts"]
min_version = "0.65"

[author]
  name = "LÃ©o De Souza"
  homepage = "https://github.com/de-souza/"
